version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev --import-realm
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak_iserv_realm.json:/opt/keycloak/data/import/keycloak_iserv_realm.json

volumes:
  keycloak_data:
